# This is a basic workflow to help you get started with Actions

name: Databricsimport

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs: 
      source_databricks_url:
        description: 'Workflow2 Name for Triggering'
        required: true
        default: 'Workflow2'
      
      source_token:
        description: 'GitHub Account Owner'
        required: true
        default: 'sumitraj0103'
      
      target_databricks_url:
        description: 'GitHub Repository Name'
        required: true
        default: 'Letsdevops'
      target_token:
        description: 'GitHub Repository Name'
        required: true
        default: 'Letsdevops'
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env: 
      pat_token: ${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}
      payload_Baseline_Number: "BSL_001"
      payload_Baseline_Revision: "zsfdgsdbgngffdwdx1dxvv2"
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with:
         python-version: 3.8 #install the python needed
         
      - name: Install dependencies
        run: |
           cd "$GITHUB_WORKSPACE/Deployment-Scripts/"
           python -m pip install --upgrade pip
           pip install -r requirements.txt
