name: Python CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel

    - name: Set version
      id: set_version
      run: echo "PACKAGE_VERSION=$(date +'%Y.%m.%d.%H%M%S')" >> $GITHUB_ENV

    - name: Build wheel
      env:
        PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
      run: |
        cd datascience_project/myfirst_project
        python setup.py sdist bdist_wheel

    - name: Create artifact
      uses: actions/upload-artifact@v3
      with:
        name: wheel-files-${{ env.PACKAGE_VERSION }}
        path: datascience_project/myfirst_project/dist/*.whl

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install datascience_project/myfirst_project/dist/*.whl

    - name: Run tests
      run: |
        pip install pytest
        pytest
