name: Application-CI-Demo11 #Name of the Workflow
on:
 workflow_dispatch
jobs: # Jobs under which it runs the Steps
  build:
    runs-on: windows-latest #Runner Declaration
    steps: # Defined Steps
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: write-host Hello, world!
  Test:
    needs: build
    runs-on: windows-latest #Runner Declaration
    steps: # Defined Steps
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: write-host Hello, world!
